name: esy - Github Action
description: Run cached esy install and esy build
inputs:
  cache-key:
    description: A cache key for esy.json/esy.lock.
    required: true
  source-cache-key:
    description: A cache key for retrieving esy sources cache.
    required: true
  working-directory:
    description: Working directory for esy
    required: false
  esy-prefix:
    description: Prefix of esy folder
    required: false
  manifest:
    description: JSON or opam file to be used
    required: false
runs:
  using: node20
  main: dist/index.js
branding:
  icon: package
  color: red
