name: esy - Github Action
description: Run cached esy install and esy build
inputs:
  cache-key:
    description: A cache key for esy.json/esy.lock.
    required: true
  source-cache-key:
    description: A cache key for retrieving esy sources cache.
    required: true
  working-directory:
    description:
      Working directory for esy. It's converted into an absolute path, if it
      already isn't
    required: false
  esy-prefix:
    description: Prefix of esy folder
    required: false
  manifest:
    description: JSON or opam file to be used
    required: false
  ocaml-compiler-version:
    description:
      Version of ocaml compiler (in semver. Eg. 5.1.0 or 4.10.1000) Optional,
      but mandatory if prepare-npm-artifacts-mode and bundle-npm-artifacts-mode
      is used. This is because, these version strings affect the relocatability
      logic while both preparation mode, and while postinstall scripts are
      generated during bundling mode.
    required: false
  ocaml-static-compiler-version:
    description:
      Version of static ocaml compiler (in semver. Eg. 5.1.0-musl.static.flambda
      or 4.10.1000-musl.static.flambda). Optional, but mandatory if
      prepare-npm-artifacts-mode and bundle-npm-artifacts-mode is used. This is
      because, these version strings affect the relocatability logic while both
      preparation mode, and while postinstall scripts are generated during
      bundling mode.
    required: false
  prepare-npm-artifacts-mode:
    description:
      Runs a steps that prepare artifacts for release the app to NPM. These
      artifacts are later used by, `bundle-npm-tarball-mode`.
    required: false
  bundle-npm-artifacts-mode:
    description: Runs a steps that bundle artifacts for release the app to NPM.
    required: false
  postinstall-js:
    description:
      Path to a custom `postinstall.js` file that could be placed in the final
      bundled NPM tarball.
    required: false
  setup-esy:
    description: Flag to control if esy itself should be installed by the action
    required: false
  setup-esy-tarball:
    description:
      URL to esy tarball. Must be provided together with shasum and version.
      Else, the action will default to latest from NPM
    required: false
  setup-esy-shasum:
    description:
      shasum of the tarball. Must be provided together with shasum and version.
      Else, the action will default to latest from NPM
    required: false
  setup-esy-version:
    description:
      version of the esy tool. Must be provided together with shasum and
      version. Else, the action will default to latest from NPM
    required: false
  setup-esy-npm-package:
    description:
      Alternative NPM package that contains esy. Can contain version/tag too. Eg
      esy@beta.
    required: false
runs:
  using: node20
  main: dist/index.js
branding:
  icon: package
  color: red
