name: esy - Github Action
description: Run cached esy install and esy build
inputs:
  cache-key:
    description: A cache key for esy.json/esy.lock.
    required: true
  source-cache-key:
    description: A cache key for retrieving esy sources cache.
    required: true
  working-directory:
    description: Working directory for esy
    required: false
  esy-prefix:
    description: Prefix of esy folder
    required: false
  manifest:
    description: JSON or opam file to be used
    required: false
  prepare-npm-artifacts-mode:
    description:
      Runs a steps that prepare artifacts for release the app to NPM. These
      artifacts are later used by, `bundle-npm-tarball-mode`
    required: false
  bundle-npm-artifacts-mode:
    description: Runs a steps that bundle artifacts for release the app to NPM.
    required: false
  postinstall-js:
    description: Path to a postinstall.js file that would be run by NPM
    required: false
runs:
  using: node20
  main: dist/index.js
branding:
  icon: package
  color: red
